name: "NX-584"
description: "Interface to GE/CaddX/NetworkX alarm systems via NX-584/NX8E"
version: "1.0.1"
slug: "nx584"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
ports:
  5007/tcp: 5007
